create or replace table `mvp-data-engineer-v1.mvp3_dataset.PRECIPITACAO` (
  DATA_HORA TIMESTAMP  NOT NULL,
  PRECIPITACAO_TOTAL FLOAT64  NOT NULL,
  RADIACAO FLOAT64 
);
ALTER TABLE `mvp-data-engineer-v1.mvp3_dataset.PRECIPITACAO`
ADD PRIMARY KEY (DATA_HORA) NOT ENFORCED;



create or replace table `mvp-data-engineer-v1.mvp3_dataset.PRESSAO` (
  DATA_HORA TIMESTAMP ,
  PRESSAO_ATMOSFERICA_NIVEL_ESTACAO FLOAT64 ,
  PRESSAO_ATMOSFERICA_MAX_HORA_ANT FLOAT64 ,
  PRESSAO_ATMOSFERICA_MIN_HORA_ANT FLOAT64 
);
ALTER TABLE `mvp-data-engineer-v1.mvp3_dataset.PRESSAO`
ADD PRIMARY KEY (DATA_HORA) NOT ENFORCED;
ALTER TABLE `mvp-data-engineer-v1.mvp3_dataset.PRESSAO`
ADD CONSTRAINT DATA_HORA_FK FOREIGN KEY (DATA_HORA)
REFERENCES `mvp-data-engineer-v1.mvp3_dataset.PRECIPITACAO`(DATA_HORA) NOT ENFORCED;


create or replace table `mvp-data-engineer-v1.mvp3_dataset.TEMPERATURA` (
  DATA_HORA TIMESTAMP ,
  TEMPERATURA_AR FLOAT64 ,
  TEMPERATURA_PONTO_ORVALHO FLOAT64 ,
  TEMPERATURA_MAXIMA_HORA_ANT FLOAT64 ,
  TEMPERATURA_MINIMA_HORA_ANT FLOAT64 ,
  TEMPERATURA_ORVALHO_MAX_HORA_ANT FLOAT64 ,
  TEMPERATURA_ORVALHO_MIN_HORA_ANT FLOAT64 
);
ALTER TABLE `mvp-data-engineer-v1.mvp3_dataset.TEMPERATURA`
ADD PRIMARY KEY (DATA_HORA) NOT ENFORCED;
ALTER TABLE `mvp-data-engineer-v1.mvp3_dataset.TEMPERATURA`
ADD CONSTRAINT DATA_HORA_FK FOREIGN KEY (DATA_HORA)
REFERENCES `mvp-data-engineer-v1.mvp3_dataset.PRECIPITACAO`(DATA_HORA) NOT ENFORCED;


create or replace table `mvp-data-engineer-v1.mvp3_dataset.UMIDADE` (
  DATA_HORA TIMESTAMP ,
  UMIDADE_REL_MAX_HORA_ANT FLOAT64 ,
  UMIDADE_REL_MIN_HORA_ANT FLOAT64 ,
  UMIDADE_RELATIVA_AR_HORARIA FLOAT64 
);
ALTER TABLE `mvp-data-engineer-v1.mvp3_dataset.UMIDADE`
ADD PRIMARY KEY (DATA_HORA) NOT ENFORCED;
ALTER TABLE `mvp-data-engineer-v1.mvp3_dataset.UMIDADE`
ADD CONSTRAINT DATA_HORA_FK FOREIGN KEY (DATA_HORA)
REFERENCES `mvp-data-engineer-v1.mvp3_dataset.PRECIPITACAO`(DATA_HORA) NOT ENFORCED;


create or replace table `mvp-data-engineer-v1.mvp3_dataset.VENTO` (
  DATA_HORA TIMESTAMP ,
  VENTO_DIRECAO_HORARIA FLOAT64 ,
  VENTO_RAJADA_MAXIMA FLOAT64 ,
  VENTO_VELOCIDADE_HORARIA FLOAT64 
);
ALTER TABLE `mvp-data-engineer-v1.mvp3_dataset.VENTO`
ADD PRIMARY KEY (DATA_HORA) NOT ENFORCED;
ALTER TABLE `mvp-data-engineer-v1.mvp3_dataset.VENTO`
ADD CONSTRAINT DATA_HORA_FK FOREIGN KEY (DATA_HORA)
REFERENCES `mvp-data-engineer-v1.mvp3_dataset.PRECIPITACAO`(DATA_HORA) NOT ENFORCED;